name: Deploy to Endora FTP

on:
  push:
    branches:
      - main  # spusť akci při pushi na větev main

jobs:
  ftp-deploy:
    name: Upload files to Endora
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Endora via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: kocicka.endora.cz
          username: bataskolahyscz
          password: Qwertz123.
          protocol: ftp
          server-dir: /web/  # změníš podle toho, kam to má na Endoře nahrávat
