name: Deploy to Endora

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload to Endora FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: kocicka.endora.cz
          username: bataskolahyscz
          password: Ab1234567890
          protocol: ftp
          port: 21
          local-dir: ./                
          server-dir: /bataskola.hys.cz/web/
